### ISSUE TITLE
Panic on macOS

### ISSUE THREAD

**Issue by BenJuan26** [timokoesters/nbodysim#1]
Compiled from source and tried to run with the default config, and it panics right away:

```
$ RUST_BACKTRACE=1 cargo run --release
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/nbodysim`
Using default config.
AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other', src/libcore/result.rs:1165:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: wgpu_device_create_compute_pipeline
  11: wgpu::Device::create_compute_pipeline
  12: nbodysim::render::run
  13: nbodysim::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start_internal
  18: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by timokoesters** [comment]
@BenJuan26 Can you give more details about your system? GPU and driver version would be useful.

**Comment by vultix** [comment]
I'm getting a very similar stacktrace:
```
AdapterInfo { name: "Intel(R) UHD Graphics 630", vendor: 0, device: 0, device_type: IntegratedGpu }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:2016:13
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: wgpu_device_create_compute_pipeline
  10: wgpu::Device::create_compute_pipeline
  11: nbodysim::render::run
  12: nbodysim::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: std::rt::lang_start_internal
  17: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm on a 2018 Macbook Pro 
Two graphics cards:

- Intel UHD Graphics 630
- Radeon Pro 560X

**Comment by BenJuan26** [comment]
Mine is a 2015 Macbook Pro with two GPUs:

- AMD Radeon R9 M370X 2 GB
- Intel Iris Pro 1536 MB

It seems in both cases the program chose the integrated graphics card, which is probably not ideal.

**Comment by timokoesters** [comment]
Can you run it without --release please?

**Comment by BenJuan26** [comment]
```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/nbodysim`
Using default config.
AdapterInfo { name: "Intel Iris Pro Graphics", vendor: 0, device: 0, device_type: IntegratedGpu }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other', src/libcore/result.rs:1165:5
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: std::panicking::try::do_call
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
   9: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  10: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  11: wgpu_native::device::device_create_compute_pipeline
             at /Users/Ben/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:2016
  12: wgpu_device_create_compute_pipeline
             at /Users/Ben/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:2036
  13: wgpu::Device::create_compute_pipeline
             at /Users/Ben/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:764
  14: nbodysim::render::run
             at src/render.rs:219
  15: nbodysim::main
             at src/main.rs:89
  16: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  17: std::panicking::try::do_call
  18: panic_unwind::dwarf::eh::read_encoded_pointer
  19: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
  20: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  21: nbodysim::default_config
```

**Comment by timokoesters** [comment]
I pushed a fix which should make it select the more powerful gpu.

**Comment by BenJuan26** [comment]
Ok I see it pick the Radeon after that fix, but still panics with the same stack trace as above.

**Comment by reem** [comment]
Seeing the same, selects the Radeon but panics in the same way.

**Comment by timokoesters** [comment]
http://shader-playground.timjones.io/4c5f5c03e2121938fb8a4cd148bc20a1

Looks like apple's "Metal" does not support doubles...
Precision is pretty important for this project, so unfortunately Apple is unsupported for now.

**Comment by BenJuan26** [comment]
Confirmed: I changed `double -> float`, `f64 -> f32`, and `dvec3 -> vec3` and it starts up, but I understand that the loss of precision will probably affect the simulation.
