### ISSUE TITLE
Panic on Linux

### ISSUE THREAD

**Issue by 01mf02** [timokoesters/nbodysim#2]
Just tried running on Linux with an Intel HD Graphics 5500 (i915):

~~~
$ RUST_BACKTRACE=1 cargo run --release
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/nbodysim`
Using default config.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::panicking::panic
             at src/libcore/panicking.rs:51
  14: wgpu_request_adapter
  15: wgpu::Adapter::request
  16: nbodysim::render::run
  17: nbodysim::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
~~~

**Comment by timokoesters** [comment]
Can you try installing mesa-vulkan-drivers and see if it works? And if not, try libvulkan-dev

**Comment by 01mf02** [comment]
Thanks, installing mesa-vulkan-drivers made it work for me.
The simulation is really impressive ...

**Comment by ghost** [comment]
Thanks. I have the same issues on Arch Linux and [Sway](https://github.com/swaywm/sway) 1.10. I already installed [vulkan-intel](https://archlinux.org/packages/extra-testing/x86_64/vulkan-intel/) and [vulkan-devel](https://archlinux.org/groups/x86_64/vulkan-devel/) (package group).

```console
$ cargo build --release
$ ./target/release/nbodysim
Using default config.
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
fish: Job 1, 'cargo run --release' terminated by signal SIGABRT (Abort)
```

**Comment by timokoesters** [comment]
I assume this can be fixed by updating all the library versions, but this will be a bit of work because many things have changed.
